params = {'ACC1': {'QQfff': [], 'TimeUS': [], 'SampleUS': [], 'AccX': [], 'AccY': [], 'AccZ': []},
'ACC2': {'QQfff': [], 'TimeUS': [], 'SampleUS': [], 'AccX': [], 'AccY': [], 'AccZ': []},
'ACC3': {'QQfff': [], 'TimeUS': [], 'SampleUS': [], 'AccX': [], 'AccY': [], 'AccZ': []},
'AETR': {'Qhhhhh': [], 'TimeUS': [], 'Ail': [], 'Elev': [], 'Thr': [], 'Rudd': [], 'Flap': []},
'AHR2': {'QccCfLLffff': [], 'TimeUS': [], 'Roll': [], 'Pitch': [], 'Yaw': [], 'Alt': [], 'Lat': [], 'Lng': [], 'Q1': [], 'Q2': [], 'Q3': [], 'Q4': []},
'AOA': {'Qff': [], 'TimeUS': [], 'AOA': [], 'SSA': []},
'ARM': {'QBH': [], 'TimeUS': [], 'ArmState': [], 'ArmChecks': []},
'ARSP': {'QffcffB': [], 'TimeUS': [], 'Airspeed': [], 'DiffPress': [], 'Temp': [], 'RawPress': [], 'Offset': [], 'U': []},
'ATRP': {'QBBcfff': [], 'TimeUS': [], 'Type': [], 'State': [], 'Servo': [], 'Demanded': [], 'Achieved': [], 'P': []},
'ATT': {'QccccCCCC': [], 'TimeUS': [], 'DesRoll': [], 'Roll': [], 'DesPitch': [], 'Pitch': [], 'DesYaw': [], 'Yaw': [], 'ErrRP': [], 'ErrYaw': []},
'BAR2': {'QffcfIff': [], 'TimeUS': [], 'Alt': [], 'Press': [], 'Temp': [], 'CRt': [], 'SMS': [], 'Offset': [], 'GndTemp': []},
'BAR3': {'QffcfIff': [], 'TimeUS': [], 'Alt': [], 'Press': [], 'Temp': [], 'CRt': [], 'SMS': [], 'Offset': [], 'GndTemp': []},
'BARO': {'QffcfIff': [], 'TimeUS': [], 'Alt': [], 'Press': [], 'Temp': [], 'CRt': [], 'SMS': [], 'Offset': [], 'GndTemp': []},
'BAT': {'Qffffcf': [], 'TimeUS': [], 'Volt': [], 'VoltR': [], 'Curr': [], 'CurrTot': [], 'Temp': [], 'Res': []},
'BAT2': {'Qffffcf': [], 'TimeUS': [], 'Volt': [], 'VoltR': [], 'Curr': [], 'CurrTot': [], 'Temp': [], 'Res': []},
'BCL': {'QfHHHHHHHHHH': [], 'TimeUS': [], 'Volt': [], 'V1': [], 'V2': [], 'V3': [], 'V4': [], 'V5': [], 'V6': [], 'V7': [], 'V8': [], 'V9': [], 'V10': []},
'BCL2': {'QfHHHHHHHHHH': [], 'TimeUS': [], 'Volt': [], 'V1': [], 'V2': [], 'V3': [], 'V4': [], 'V5': [], 'V6': [], 'V7': [], 'V8': [], 'V9': [], 'V10': []},
'BCN': {'QBBfffffff': [], 'TimeUS': [], 'Health': [], 'Cnt': [], 'D0': [], 'D1': [], 'D2': [], 'D3': [], 'PosX': [], 'PosY': [], 'PosZ': []},
'CAM': {'QIHLLeeeccC': [], 'TimeUS': [], 'GPSTime': [], 'GPSWeek': [], 'Lat': [], 'Lng': [], 'Alt': [], 'RelAlt': [], 'GPSAlt': [], 'Roll': [], 'Pitch': [], 'Yaw': []},
'CMD': {'QHHHfffffff': [], 'TimeUS': [], 'CTot': [], 'CNum': [], 'CId': [], 'Prm1': [], 'Prm2': [], 'Prm3': [], 'Prm4': [], 'Lat': [], 'Lng': [], 'Alt': []},
'CTUN': {'Qcccchhhf': [], 'TimeUS': [], 'NavRoll': [], 'Roll': [], 'NavPitch': [], 'Pitch': [], 'ThrOut': [], 'RdrOut': [], 'ThrDem': [], 'Aspd': []},
'DMS': {'IIIIIBBBBBBBBBB': [], 'TimeMS': [], 'N': [], 'Dp': [], 'RT': [], 'RS': [], 'Er': [], 'Fa': [], 'Fmn': [], 'Fmx': [], 'Pa': [], 'Pmn': [], 'Pmx': [], 'Sa': [], 'Smn': [], 'Smx': []},
'DSF': {'QIBHIIII': [], 'TimeUS': [], 'Dp': [], 'IErr': [], 'Blk': [], 'Bytes': [], 'FMn': [], 'FMx': [], 'FAv': []},
'DSTL': {'QBfLLeccfeffff': [], 'TimeUS': [], 'Stg': [], 'THdg': [], 'Lat': [], 'Lng': [], 'Alt': [], 'XT': [], 'Travel': [], 'L1I': [], 'Loiter': [], 'Des': [], 'P': [], 'I': [], 'D': []},
'ESC1': {'Qcccc': [], 'TimeUS': [], 'RPM': [], 'Volt': [], 'Curr': [], 'Temp': []},
'ESC2': {'Qcccc': [], 'TimeUS': [], 'RPM': [], 'Volt': [], 'Curr': [], 'Temp': []},
'ESC3': {'Qcccc': [], 'TimeUS': [], 'RPM': [], 'Volt': [], 'Curr': [], 'Temp': []},
'ESC4': {'Qcccc': [], 'TimeUS': [], 'RPM': [], 'Volt': [], 'Curr': [], 'Temp': []},
'ESC5': {'Qcccc': [], 'TimeUS': [], 'RPM': [], 'Volt': [], 'Curr': [], 'Temp': []},
'ESC6': {'Qcccc': [], 'TimeUS': [], 'RPM': [], 'Volt': [], 'Curr': [], 'Temp': []},
'ESC7': {'Qcccc': [], 'TimeUS': [], 'RPM': [], 'Volt': [], 'Curr': [], 'Temp': []},
'ESC8': {'Qcccc': [], 'TimeUS': [], 'RPM': [], 'Volt': [], 'Curr': [], 'Temp': []},
'FMT': {'BBnNZ': [], 'Type': [], 'Length': [], 'Name': [], 'Format': [], 'Columns': []},
'GMB1': {'Iffffffffff': [], 'TimeMS': [], 'dt': [], 'dax': [], 'day': [], 'daz': [], 'dvx': [], 'dvy': [], 'dvz': [], 'jx': [], 'jy': [], 'jz': []},
'GMB2': {'IBfffffffff': [], 'TimeMS': [], 'es': [], 'ex': [], 'ey': [], 'ez': [], 'rx': [], 'ry': [], 'rz': [], 'tx': [], 'ty': [], 'tz': []},
'GMB3': {'Ihhh': [], 'TimeMS': [], 'rl_torque_cmd': [], 'el_torque_cmd': [], 'az_torque_cmd': []},
'GPA': {'QCCCCBIH': [], 'TimeUS': [], 'VDop': [], 'HAcc': [], 'VAcc': [], 'SAcc': [], 'VV': [], 'SMS': [], 'Delta': []},
'GPA2': {'QCCCCBIH': [], 'TimeUS': [], 'VDop': [], 'HAcc': [], 'VAcc': [], 'SAcc': [], 'VV': [], 'SMS': [], 'Delta': []},
'GPAB': {'QCCCCBIH': [], 'TimeUS': [], 'VDop': [], 'HAcc': [], 'VAcc': [], 'SAcc': [], 'VV': [], 'SMS': [], 'Delta': []},
'GPS': {'QBIHBcLLefffB': [], 'TimeUS': [], 'Status': [], 'GMS': [], 'GWk': [], 'NSats': [], 'HDop': [], 'Lat': [], 'Lng': [], 'Alt': [], 'Spd': [], 'GCrs': [], 'VZ': [], 'U': []},
'GPS2': {'QBIHBcLLefffB': [], 'TimeUS': [], 'Status': [], 'GMS': [], 'GWk': [], 'NSats': [], 'HDop': [], 'Lat': [], 'Lng': [], 'Alt': [], 'Spd': [], 'GCrs': [], 'VZ': [], 'U': []},
'GPSB': {'QBIHBcLLefffB': [], 'TimeUS': [], 'Status': [], 'GMS': [], 'GWk': [], 'NSats': [], 'HDop': [], 'Lat': [], 'Lng': [], 'Alt': [], 'Spd': [], 'GCrs': [], 'VZ': [], 'U': []},
'GRAW': {'QIHBBddfBbB': [], 'TimeUS': [], 'WkMS': [], 'Week': [], 'numSV': [], 'sv': [], 'cpMes': [], 'prMes': [], 'doMes': [], 'mesQI': [], 'cno': [], 'lli': []},
'GRXH': {'QdHbBB': [], 'TimeUS': [], 'rcvTime': [], 'week': [], 'leapS': [], 'numMeas': [], 'recStat': []},
'GRXS': {'QddfBBBHBBBBB': [], 'TimeUS': [], 'prMes': [], 'cpMes': [], 'doMes': [], 'gnss': [], 'sv': [], 'freq': [], 'lock': [], 'cno': [], 'prD': [], 'cpD': [], 'doD': [], 'trk': []},
'GSPD': {'Qffff': [], 'TimeUS': [], 'thrDem': [], 'GSPDthr': [], 'PErr': [], 'EDelta': []},
'GYR1': {'QQfff': [], 'TimeUS': [], 'SampleUS': [], 'GyrX': [], 'GyrY': [], 'GyrZ': []},
'GYR2': {'QQfff': [], 'TimeUS': [], 'SampleUS': [], 'GyrX': [], 'GyrY': [], 'GyrZ': []},
'GYR3': {'QQfff': [], 'TimeUS': [], 'SampleUS': [], 'GyrX': [], 'GyrY': [], 'GyrZ': []},
'IMT': {'Qfffffffff': [], 'TimeUS': [], 'DelT': [], 'DelvT': [], 'DelaT': [], 'DelAX': [], 'DelAY': [], 'DelAZ': [], 'DelVX': [], 'DelVY': [], 'DelVZ': []},
'IMT2': {'Qfffffffff': [], 'TimeUS': [], 'DelT': [], 'DelvT': [], 'DelaT': [], 'DelAX': [], 'DelAY': [], 'DelAZ': [], 'DelVX': [], 'DelVY': [], 'DelVZ': []},
'IMT3': {'Qfffffffff': [], 'TimeUS': [], 'DelT': [], 'DelvT': [], 'DelaT': [], 'DelAX': [], 'DelAY': [], 'DelAZ': [], 'DelVX': [], 'DelVY': [], 'DelVZ': []},
'IMU': {'QffffffIIfBBHH': [], 'TimeUS': [], 'GyrX': [], 'GyrY': [], 'GyrZ': [], 'AccX': [], 'AccY': [], 'AccZ': [], 'EG': [], 'EA': [], 'T': [], 'GH': [], 'AH': [], 'GHz': [], 'AHz': []},
'IMU2': {'QffffffIIfBBHH': [], 'TimeUS': [], 'GyrX': [], 'GyrY': [], 'GyrZ': [], 'AccX': [], 'AccY': [], 'AccZ': [], 'EG': [], 'EA': [], 'T': [], 'GH': [], 'AH': [], 'GHz': [], 'AHz': []},
'IMU3': {'QffffffIIfBBHH': [], 'TimeUS': [], 'GyrX': [], 'GyrY': [], 'GyrZ': [], 'AccX': [], 'AccY': [], 'AccZ': [], 'EG': [], 'EA': [], 'T': [], 'GH': [], 'AH': [], 'GHz': [], 'AHz': []},
'ISBD': {'QHHaaa': [], 'TimeUS': [], 'N': [], 'seqno': [], 'x': [], 'y': [], 'z': []},
'ISBH': {'QHBBHHQf': [], 'TimeUS': [], 'N': [], 'type': [], 'instance': [], 'mul': [], 'smp_cnt': [], 'SampleUS': [], 'smp_rate': []},
'LAND': {'QBBBfff': [], 'TimeUS': [], 'stage': [], 'f1': [], 'f2': [], 'slope': [], 'slopeInit': [], 'altO': []},
'MAG': {'QhhhhhhhhhBI': [], 'TimeUS': [], 'MagX': [], 'MagY': [], 'MagZ': [], 'OfsX': [], 'OfsY': [], 'OfsZ': [], 'MOfsX': [], 'MOfsY': [], 'MOfsZ': [], 'Health': [], 'S': []},
'MAG2': {'QhhhhhhhhhBI': [], 'TimeUS': [], 'MagX': [], 'MagY': [], 'MagZ': [], 'OfsX': [], 'OfsY': [], 'OfsZ': [], 'MOfsX': [], 'MOfsY': [], 'MOfsZ': [], 'Health': [], 'S': []},
'MAG3': {'QhhhhhhhhhBI': [], 'TimeUS': [], 'MagX': [], 'MagY': [], 'MagZ': [], 'OfsX': [], 'OfsY': [], 'OfsZ': [], 'MOfsX': [], 'MOfsY': [], 'MOfsZ': [], 'Health': [], 'S': []},
'MODE': {'QMBB': [], 'TimeUS': [], 'Mode': [], 'ModeNum': [], 'Rsn': []},
'MSG': {'QZ': [], 'TimeUS': [], 'Message': []},
'NKF0': {'QBccCCcccccccc': [], 'TimeUS': [], 'ID': [], 'rng': [], 'innov': [], 'SIV': [], 'TR': [], 'BPN': [], 'BPE': [], 'BPD': [], 'OFH': [], 'OFL': [], 'OFN': [], 'OFE': [], 'OFD': []},
'NKF1': {'QccCfffffffccce': [], 'TimeUS': [], 'Roll': [], 'Pitch': [], 'Yaw': [], 'VN': [], 'VE': [], 'VD': [], 'dPD': [], 'PN': [], 'PE': [], 'PD': [], 'GX': [], 'GY': [], 'GZ': [], 'OH': []},
'NKF2': {'QbccccchhhhhhB': [], 'TimeUS': [], 'AZbias': [], 'GSX': [], 'GSY': [], 'GSZ': [], 'VWN': [], 'VWE': [], 'MN': [], 'ME': [], 'MD': [], 'MX': [], 'MY': [], 'MZ': [], 'MI': []},
'NKF3': {'Qcccccchhhcc': [], 'TimeUS': [], 'IVN': [], 'IVE': [], 'IVD': [], 'IPN': [], 'IPE': [], 'IPD': [], 'IMX': [], 'IMY': [], 'IMZ': [], 'IYAW': [], 'IVT': []},
'NKF4': {'QcccccfbbHBHHb': [], 'TimeUS': [], 'SV': [], 'SP': [], 'SH': [], 'SM': [], 'SVT': [], 'errRP': [], 'OFN': [], 'OFE': [], 'FS': [], 'TS': [], 'SS': [], 'GPS': [], 'PI': []},
'NKF5': {'QBhhhcccCCfff': [], 'TimeUS': [], 'NI': [], 'FIX': [], 'FIY': [], 'AFI': [], 'HAGL': [], 'offset': [], 'RI': [], 'rng': [], 'Herr': [], 'eAng': [], 'eVel': [], 'ePos': []},
'NKF6': {'QccCfffffffccce': [], 'TimeUS': [], 'Roll': [], 'Pitch': [], 'Yaw': [], 'VN': [], 'VE': [], 'VD': [], 'dPD': [], 'PN': [], 'PE': [], 'PD': [], 'GX': [], 'GY': [], 'GZ': [], 'OH': []},
'NKF7': {'QbccccchhhhhhB': [], 'TimeUS': [], 'AZbias': [], 'GSX': [], 'GSY': [], 'GSZ': [], 'VWN': [], 'VWE': [], 'MN': [], 'ME': [], 'MD': [], 'MX': [], 'MY': [], 'MZ': [], 'MI': []},
'NKF8': {'Qcccccchhhcc': [], 'TimeUS': [], 'IVN': [], 'IVE': [], 'IVD': [], 'IPN': [], 'IPE': [], 'IPD': [], 'IMX': [], 'IMY': [], 'IMZ': [], 'IYAW': [], 'IVT': []},
'NKF9': {'QcccccfbbHBHHb': [], 'TimeUS': [], 'SV': [], 'SP': [], 'SH': [], 'SM': [], 'SVT': [], 'errRP': [], 'OFN': [], 'OFE': [], 'FS': [], 'TS': [], 'SS': [], 'GPS': [], 'PI': []},
'NKQ1': {'Qffff': [], 'TimeUS': [], 'Q1': [], 'Q2': [], 'Q3': [], 'Q4': []},
'NKQ2': {'Qffff': [], 'TimeUS': [], 'Q1': [], 'Q2': [], 'Q3': [], 'Q4': []},
'NTUN': {'Qfcccfff': [], 'TimeUS': [], 'WpDist': [], 'TargBrg': [], 'NavBrg': [], 'AltErr': [], 'XT': [], 'XTi': [], 'ArspdErr': []},
'OF': {'QBffff': [], 'TimeUS': [], 'Qual': [], 'flowX': [], 'flowY': [], 'bodyX': [], 'bodyY': []},
'ORGN': {'QBLLe': [], 'TimeUS': [], 'Type': [], 'Lat': [], 'Lng': [], 'Alt': []},
'PARM': {'QNf': [], 'TimeUS': [], 'Name': [], 'Value': []},
'PIDA': {'Qffffff': [], 'TimeUS': [], 'Des': [], 'P': [], 'I': [], 'D': [], 'FF': [], 'AFF': []},
'PIDP': {'Qffffff': [], 'TimeUS': [], 'Des': [], 'P': [], 'I': [], 'D': [], 'FF': [], 'AFF': []},
'PIDR': {'Qffffff': [], 'TimeUS': [], 'Des': [], 'P': [], 'I': [], 'D': [], 'FF': [], 'AFF': []},
'PIDS': {'Qffffff': [], 'TimeUS': [], 'Des': [], 'P': [], 'I': [], 'D': [], 'FF': [], 'AFF': []},
'PIDY': {'Qffffff': [], 'TimeUS': [], 'Des': [], 'P': [], 'I': [], 'D': [], 'FF': [], 'AFF': []},
'PIQA': {'Qffffff': [], 'TimeUS': [], 'Des': [], 'P': [], 'I': [], 'D': [], 'FF': [], 'AFF': []},
'PIQP': {'Qffffff': [], 'TimeUS': [], 'Des': [], 'P': [], 'I': [], 'D': [], 'FF': [], 'AFF': []},
'PIQR': {'Qffffff': [], 'TimeUS': [], 'Des': [], 'P': [], 'I': [], 'D': [], 'FF': [], 'AFF': []},
'PIQY': {'Qffffff': [], 'TimeUS': [], 'Des': [], 'P': [], 'I': [], 'D': [], 'FF': [], 'AFF': []},
'PM': {'QHHIIII': [], 'TimeUS': [], 'NLon': [], 'NLoop': [], 'MaxT': [], 'MinT': [], 'LogDrop': [], 'Mem': []},
'POS': {'QLLfff': [], 'TimeUS': [], 'Lat': [], 'Lng': [], 'Alt': [], 'RelHomeAlt': [], 'RelOriginAlt': []},
'POWR': {'QffH': [], 'TimeUS': [], 'Vcc': [], 'VServo': [], 'Flags': []},
'PRX': {'QBfffffffffff': [], 'TimeUS': [], 'Health': [], 'D0': [], 'D45': [], 'D90': [], 'D135': [], 'D180': [], 'D225': [], 'D270': [], 'D315': [], 'DUp': [], 'CAn': [], 'CDis': []},
'QTUN': {'Qffffhhfffff': [], 'TimeUS': [], 'AngBst': [], 'ThrOut': [], 'DAlt': [], 'Alt': [], 'DCRt': [], 'CRt': [], 'DVx': [], 'DVy': [], 'DAx': [], 'DAy': [], 'TMix': []},
'RAD': {'QBBBBBHH': [], 'TimeUS': [], 'RSSI': [], 'RemRSSI': [], 'TxBuf': [], 'Noise': [], 'RemNoise': [], 'RxErrors': [], 'Fixed': []},
'RALY': {'QBBLLh': [], 'TimeUS': [], 'Tot': [], 'Seq': [], 'Lat': [], 'Lng': [], 'Alt': []},
'RATE': {'Qffffffffffff': [], 'TimeUS': [], 'RDes': [], 'R': [], 'ROut': [], 'PDes': [], 'P': [], 'POut': [], 'YDes': [], 'Y': [], 'YOut': [], 'ADes': [], 'A': [], 'AOut': []},
'RCIN': {'QHHHHHHHHHHHHHH': [], 'TimeUS': [], 'C1': [], 'C2': [], 'C3': [], 'C4': [], 'C5': [], 'C6': [], 'C7': [], 'C8': [], 'C9': [], 'C10': [], 'C11': [], 'C12': [], 'C13': [], 'C14': []},
'RCOU': {'QHHHHHHHHHHHHHH': [], 'TimeUS': [], 'C1': [], 'C2': [], 'C3': [], 'C4': [], 'C5': [], 'C6': [], 'C7': [], 'C8': [], 'C9': [], 'C10': [], 'C11': [], 'C12': [], 'C13': [], 'C14': []},
'RFND': {'QCBCB': [], 'TimeUS': [], 'Dist1': [], 'Orient1': [], 'Dist2': [], 'Orient2': []},
'RPM': {'Qff': [], 'TimeUS': [], 'rpm1': [], 'rpm2': []},
'RSSI': {'Qf': [], 'TimeUS': [], 'RXRSSI': []},
'SBFE': {'QIHBBdddfffff': [], 'TimeUS': [], 'TOW': [], 'WN': [], 'Mode': [], 'Err': [], 'Lat': [], 'Lng': [], 'Height': [], 'Undul': [], 'Vn': [], 'Ve': [], 'Vu': [], 'COG': []},
'SBPH': {'QIII': [], 'TimeUS': [], 'CrcError': [], 'LastInject': [], 'IARhyp': []},
'SBRE': {'QHIiBB': [], 'TimeUS': [], 'GWk': [], 'GMS': [], 'ns_residual': [], 'level': [], 'quality': []},
'SBRH': {'QQQQQQQQ': [], 'TimeUS': [], 'msg_flag': [], '1': [], '2': [], '3': [], '4': [], '5': [], '6': []},
'SBRM': {'QQQQQQQQQQQQQQQ': [], 'TimeUS': [], 'msg_flag': [], '1': [], '2': [], '3': [], '4': [], '5': [], '6': [], '7': [], '8': [], '9': [], '10': [], '11': [], '12': [], '13': []},
'SIM': {'QccCfLLffff': [], 'TimeUS': [], 'Roll': [], 'Pitch': [], 'Yaw': [], 'Alt': [], 'Lat': [], 'Lng': [], 'Q1': [], 'Q2': [], 'Q3': [], 'Q4': []},
'SONR': {'QffBf': [], 'TimeUS': [], 'Dist': [], 'Volt': [], 'Cnt': [], 'Corr': []},
'SRTL': {'QBHHBfff': [], 'TimeUS': [], 'Active': [], 'NumPts': [], 'MaxPts': [], 'Action': [], 'N': [], 'E': [], 'D': []},
'STAT': {'QBfBBBBBB': [], 'TimeUS': [], 'isFlying': [], 'isFlyProb': [], 'Armed': [], 'Safety': [], 'Crash': [], 'Still': [], 'Stage': [], 'Hit': []},
'STRT': {'QBH': [], 'TimeUS': [], 'SType': [], 'CTot': []},
'TEC2': {'Qffff': [], 'TimeUS': [], 'KErr': [], 'PErr': [], 'EDelta': [], 'LF': []},
'TECS': {'QfffffffffffffB': [], 'TimeUS': [], 'h': [], 'dh': [], 'hdem': [], 'dhdem': [], 'spdem': [], 'sp': [], 'dsp': [], 'ith': [], 'iph': [], 'th': [], 'ph': [], 'dspdem': [], 'w': [], 'f': []},
'TERR': {'QBLLHffHH': [], 'TimeUS': [], 'Status': [], 'Lat': [], 'Lng': [], 'Spacing': [], 'TerrH': [], 'CHeight': [], 'Pending': [], 'Loaded': []},
'TRIG': {'QIHLLeeeccC': [], 'TimeUS': [], 'GPSTime': [], 'GPSWeek': [], 'Lat': [], 'Lng': [], 'Alt': [], 'RelAlt': [], 'GPSAlt': [], 'Roll': [], 'Pitch': [], 'Yaw': []},
'UBX1': {'QBHBBHI': [], 'TimeUS': [], 'Instance': [], 'noisePerMS': [], 'jamInd': [], 'aPower': [], 'agcCnt': [], 'config': []},
'UBX2': {'QBbBbB': [], 'TimeUS': [], 'Instance': [], 'ofsI': [], 'magI': [], 'ofsQ': [], 'magQ': []},
'UBY1': {'QBHBBHI': [], 'TimeUS': [], 'Instance': [], 'noisePerMS': [], 'jamInd': [], 'aPower': [], 'agcCnt': [], 'config': []},
'UBY2': {'QBbBbB': [], 'TimeUS': [], 'Instance': [], 'ofsI': [], 'magI': [], 'ofsQ': [], 'magQ': []},
'VIBE': {'QfffIII': [], 'TimeUS': [], 'VibeX': [], 'VibeY': [], 'VibeZ': [], 'Clip0': [], 'Clip1': [], 'Clip2': []},
'VISO': {'Qffffffff': [], 'TimeUS': [], 'dt': [], 'AngDX': [], 'AngDY': [], 'AngDZ': [], 'PosDX': [], 'PosDY': [], 'PosDZ': [], 'conf': []},
'XKF0': {'QBccCCcccccccc': [], 'TimeUS': [], 'ID': [], 'rng': [], 'innov': [], 'SIV': [], 'TR': [], 'BPN': [], 'BPE': [], 'BPD': [], 'OFH': [], 'OFL': [], 'OFN': [], 'OFE': [], 'OFD': []},
'XKF1': {'QccCfffffffccce': [], 'TimeUS': [], 'Roll': [], 'Pitch': [], 'Yaw': [], 'VN': [], 'VE': [], 'VD': [], 'dPD': [], 'PN': [], 'PE': [], 'PD': [], 'GX': [], 'GY': [], 'GZ': [], 'OH': []},
'XKF2': {'QccccchhhhhhB': [], 'TimeUS': [], 'AX': [], 'AY': [], 'AZ': [], 'VWN': [], 'VWE': [], 'MN': [], 'ME': [], 'MD': [], 'MX': [], 'MY': [], 'MZ': [], 'MI': []},
'XKF3': {'Qcccccchhhcc': [], 'TimeUS': [], 'IVN': [], 'IVE': [], 'IVD': [], 'IPN': [], 'IPE': [], 'IPD': [], 'IMX': [], 'IMY': [], 'IMZ': [], 'IYAW': [], 'IVT': []},
'XKF4': {'QcccccfbbHBHHb': [], 'TimeUS': [], 'SV': [], 'SP': [], 'SH': [], 'SM': [], 'SVT': [], 'errRP': [], 'OFN': [], 'OFE': [], 'FS': [], 'TS': [], 'SS': [], 'GPS': [], 'PI': []},
'XKF5': {'QBhhhcccCCfff': [], 'TimeUS': [], 'NI': [], 'FIX': [], 'FIY': [], 'AFI': [], 'HAGL': [], 'offset': [], 'RI': [], 'rng': [], 'Herr': [], 'eAng': [], 'eVel': [], 'ePos': []},
'XKF6': {'QccCfffffffccce': [], 'TimeUS': [], 'Roll': [], 'Pitch': [], 'Yaw': [], 'VN': [], 'VE': [], 'VD': [], 'dPD': [], 'PN': [], 'PE': [], 'PD': [], 'GX': [], 'GY': [], 'GZ': [], 'OH': []},
'XKF7': {'QccccchhhhhhB': [], 'TimeUS': [], 'AX': [], 'AY': [], 'AZ': [], 'VWN': [], 'VWE': [], 'MN': [], 'ME': [], 'MD': [], 'MX': [], 'MY': [], 'MZ': [], 'MI': []},
'XKF8': {'Qcccccchhhcc': [], 'TimeUS': [], 'IVN': [], 'IVE': [], 'IVD': [], 'IPN': [], 'IPE': [], 'IPD': [], 'IMX': [], 'IMY': [], 'IMZ': [], 'IYAW': [], 'IVT': []},
'XKF9': {'QcccccfbbHBHHb': [], 'TimeUS': [], 'SV': [], 'SP': [], 'SH': [], 'SM': [], 'SVT': [], 'errRP': [], 'OFN': [], 'OFE': [], 'FS': [], 'TS': [], 'SS': [], 'GPS': [], 'PI': []},
'XKFD': {'Qffffff': [], 'TimeUS': [], 'IX': [], 'IY': [], 'IZ': [], 'IVX': [], 'IVY': [], 'IVZ': []},
'XKQ1': {'Qffff': [], 'TimeUS': [], 'Q1': [], 'Q2': [], 'Q3': [], 'Q4': []},
'XKQ2': {'Qffff': [], 'TimeUS': [], 'Q1': [], 'Q2': [], 'Q3': [], 'Q4': []},
'XKV1': {'Qffffffffffff': [], 'TimeUS': [], 'V00': [], 'V01': [], 'V02': [], 'V03': [], 'V04': [], 'V05': [], 'V06': [], 'V07': [], 'V08': [], 'V09': [], 'V10': [], 'V11': []},
'XKV2': {'Qffffffffffff': [], 'TimeUS': [], 'V12': [], 'V13': [], 'V14': [], 'V15': [], 'V16': [], 'V17': [], 'V18': [], 'V19': [], 'V20': [], 'V21': [], 'V22': [], 'V23': []}}